### ISSUE TITLE
Usar addon con Jellyfin

### ISSUE THREAD

**Issue by francocalvo** [mariano-git/plugin.video.flow#1]
Capaz esto esta recontra agarrado de los pelos, pero es lo unico relacionado que encontré. Teniendo Cablevision Flow con el box y todo, es posible conseguir usar la función de Live TV en Jellyfin? Estuve intentando entender este plugin y tengo la sensación que si, pero no estoy lo suficientemente interiorizado. 

Se requiere: un tuner que puede ser M3U o HD Homeruner y XMLTV

**Comment by mariano-git** [comment]
Entiendo que algunas partes del codigo podrian servirte para poder hacer algo. De todas maneras no conozco como funciona Jellyfin y el codigo esta pensado para kodi

**Comment by Panderine** [comment]
Estoy en la misma búsqueda que @CalvoUTN. Jellyfin/telly/tvheadend actuan de "proxys" de IPTV. Básicamente levantas listas m3u con los canales y podes reproducir los streams esos en cualquier cliente  (son como kodi pero versión cliente - servidor). La pregunta del millón es como extraer los links a los canales de stream de la app de flow.

Por lo que veo del código, llamas a una API y terminas accediendo por web.flow.com.ar, básicamente es un parser del cliente web común, verdad?. No parece que Flow publique sus streams en formado m3u o dash...

**Comment by mariano-git** [comment]
Hola @Panderine Es tal cual vos lo decis... Flow no publica un feed standard, tiene formato propietario. Los streams si son DASH pero estan DRM protected.
