### ISSUE TITLE
Que paso?

### ISSUE THREAD

**Issue by TimmyOtools** [mariano-git/plugin.video.flow#12]
No funciona mas?

**Comment by mariano-git** [comment]
Hola @TimmyOtools .
No tengo reportes de que no este funcionando... 
Podes mandarme mas datos?

**Comment by TimmyOtools** [comment]
Yo lo instalé en kodi 20.1 Nexus en pc para probar y cuando ingresé no apareció nada. Hasta probe cambiando el host web.app.flow.com.ar y nada

**Comment by mariano-git** [comment]
Ahh, ta bien, si en KODI 20 no lo probe todavia porque en linux no tenia soporte de IPTV Simple y no funcionaba.
En KODI 19 deberia funcionar correctamente

**Comment by mariano-git** [comment]
Cerrando issue porque la version de KODI aun no esta soportada
