### ISSUE TITLE
Kodi 20 Nexus

### ISSUE THREAD

**Issue by pikenon** [mariano-git/plugin.video.flow#13]
Seguramente es tonta la pregunta porque está aclarado que funciona con KODI 19 MATRIX.
Pero no hay perspectivas de qué funcione para KODI 20 MATRIX? O bien cuál es el impedimento técnico para que funcione?
Gracias de antemano, Saludos!!

**Comment by mariano-git** [comment]
Hola @pikenon !!

Perdon por la demora en contestar. 
Dentro de poco va a haber novedades, pero como estoy laburando solo en el proyecto, a veces se hace largo.

Saludos!

**Comment by mariano-git** [comment]
Hola @pikenon 

Sigamos aca https://github.com/mariano-git/plugin.video.flow/issues/16
