### ISSUE TITLE
[Personal flow error] - 

### ISSUE THREAD

**Issue by nmapper** [mariano-git/plugin.video.flow#15]
I have days with this error.

Looking in the logs i found this:

`requests.exceptions.HTTPError: 509 Server Error: Unknown Code for url: https://web.flow.com.ar/auth/v2/provision/login`

Pasting the url above in my local PC i see the error 509. **I know this is not a bug**, but the web service on flow still working.

¿maybe the url was changed?

**Comment by SanSan74** [comment]
No soy especialista, pero me parece que el URL del Auth cambio a 

https://web.app.flow.com.ar/auth/v2/provision/login

**Comment by mariano-git** [comment]
Pronto volvemos!!!

![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/a7fb3744-5cdb-42a1-bc2b-67c0b0f0d593)

**Comment by mariano-git** [comment]
Hola @SanSan74, @nmapper 

Sigamos aca https://github.com/mariano-git/plugin.video.flow/issues/16
