### ISSUE TITLE
Release 1.5.1

### ISSUE THREAD

**Issue by mariano-git** [mariano-git/plugin.video.flow#16]
Hola!

Una nueva version esta disponible para descargar usando el repositorio.
Seria aconsejable que borren la version vieja si es que todavia la tienen instalada. 
Cierro los otros issues y sigamos en este los problemas de puesta en funcionamiento y si vemos algo nuevo creamos una issue nueva.

Saludos!!
Mariano

**Comment by mariano-git** [comment]
![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/ab53018e-e127-469c-bf0a-266531244f2a)

**Comment by pikenon** [comment]
Buena noticia!
Pero recién, rápidamente y sin probar demasiado, eliminé el add-on anterior e instalé el nuevo (1.5.1).
Por ahora no logro que me vuelvan a aparecer los canales.
Ya configuré la cuenta correctamente pero me sigue dando este error cada vez que arranco KODI 20.2: IPTV Simple Client - connection lost.
Y si me meto al menú "TV" (dónde antes me aparecían todos los canaleS), ahora se queda eternamente en "PVR Manager is starting up 0%" (y se queda siempre en 0%). 
Van capturas:

![image](https://github.com/mariano-git/plugin.video.flow/assets/73316976/ef5b4ad9-c554-44c7-bbd8-f070347df590)

![image](https://github.com/mariano-git/plugin.video.flow/assets/73316976/0a4a5888-e7e9-4f2d-bbe8-afb4c91db640)

En mi caso lo uso en Windows 10 y en Android. Me pasa lo mismo en ambos OS.

**Comment by MaxiReggi** [comment]
Hola @mariano-git! Genial lo del nuevo release! Hoy lo voy a probar!

Respecto al problema del Unauthorized que tenía previamente, lo "solucioné" tocando un poco el código y guardando el cache token que te devuelve el login en el settings.xml del addon, en la property "jwt" más específicamente.

Hoy voy a probar este nuevo release y después comento qué tal me va!

Muchas gracias como siempre!!!

**Comment by mariano-git** [comment]
Hola @pikenon Fijate en PVR IPTV Simple si las rutas a los archivos estan bien o sino en la configuracion del plugin date a Autoconfigure IPTV Simple.
![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/fb6a4a9f-60ac-4794-a5d7-ee6595d32f57)

**Comment by mariano-git** [comment]
Hola @MaxiReggi Por lo que vi es un poco mas complicado que eso. Pero barbaro que lo hiciste funcionar!!
Avisame como te va con esta nueva version que agrega Radios y esta preparada para cargar contenido on Demand a futuro.

![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/a22aa261-0313-4450-9345-c64ecc41832f)

**Comment by MarcoMiretti** [comment]
Buenas @mariano-git ! Gracias por el laburo, que buena pinta tiene la nueva versión

Por el momento lo probé medio rápido desinstalando e instalando de nuevo (configuré IPTV), pero no me está saltando nada en TV (similar a lo que comenta @pikenon), miré el log y lo que tira es esto, todavía no me pude poner a debuggear mucho.

Lo estoy usando en kodi 19.5 matrix arriba de un LibreELEC en una raspberri pi 4.

[log-marco.log](https://github.com/mariano-git/plugin.video.flow/files/12095566/log-marco.log)

**Comment by mariano-git** [comment]
Hola @MarcoMiretti 

El error es una perdida de conexion o mucha demora en obtener datos desde la conexion a los servidores y `urllib/request.py` cerro la conexion. 

Asegurate de tener una buena conexion desde el box donde estes usando el kodi y probar nuevamente.
Usualmente demora bastante en obtener la programacion, pero los canales deberia traerlos rapido

**Comment by MaxiReggi** [comment]
Hola @mariano-git !!

Comencé con la prueba de la nueva versión. Desinstalé el .zip que yo había modificado, volví el Simple IPTV Client a los valores por defecto de configuración, volví a instalar la nueva versión 1.5.1 desde el repo, puse user y clave, y luego le di a configurar IPTV Simple automáticamente en la sección EGP, pero me tira una excepción por lo que veo el módulo Restful de Piggy.

Lo que no estoy viendo son los archivos xml y m3u en el directorio de configuración del addon, sólo veo el settings, pero entiendo que esos archivos los genera luego de darle a "Configurar automáticamente Simple IPTV Client", que es donde está fallando.

Te copio el log!
[log-maxi.log](https://github.com/mariano-git/plugin.video.flow/files/12095542/log-maxi.log)


Saludos y gracias!

**Comment by mariano-git** [comment]
@MaxiReggi Eso es rarisimo!! 404 en la url del login...

`[https://web.flow.com.ar:443](https://web.flow.com.ar/) "POST /auth/v2/provision/login HTTP/1.1" 404 377`

HTTP​ 404 Not Found o HTTP 404 No Encontrado es un código de estado HTTP que indica que el host ha sido capaz de comunicarse con el servidor, pero no existe el recurso que pediste (/auth/v2/provision/login).

`ws.rs.notfoundexception.NotFoundException`  de PiggyWS...

Me huele a algun cambio raro que hayas hecho o a un bug en la version de urllib3.
Tendriamos que asegurarnos de 2 cosas.

1.- que no hayas hecho ningun cambio mientras hacias pruebas cuando no andaba.
2.- que el urllib3 no este agregando el 443 al final de la url xq ya es https...

2023-07-19 08:58:00.521 T:561 DEBUG : plugin.video.flow: DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): web.flow.com.ar:**443**
2023-07-19 08:58:00.850 T:561 DEBUG : plugin.video.flow: DEBUG: urllib3.connectionpool: [**https**://web.flow.com.ar:**443**](**https**://web.flow.com.ar/) "POST /auth/v2/provision/login HTTP/1.1" 404 377

**https + 443 Error seguro....**

Proba desde la consola de comandos esto: (probablemente tengas que instalar **curl**, o por ahi no...)

```
curl 'https://web.flow.com.ar/auth/v2/provision/login' \
  -H 'authority: web.flow.com.ar' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,es;q=0.8' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'origin: https://web.app.flow.com.ar' \
  -H 'referer: https://web.app.flow.com.ar/' \
  -H 'sec-ch-ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36' \
  -H 'x-request-id: web-3.73.3-51167608-997e57c8' \
  --data-raw '{"accountId":"**tu usuario**","password":"**tu password**","deviceName":"Linux x86_64","deviceType":"WEB","devicePlatform":"WINDOWS","clientCasId":"CAFEBABEBADBABE","version":"3.73.3","type":"CVA","deviceModel":"PC","company":"flow"}' \
  --compressed

```

**Comment by MaxiReggi** [comment]
Listo @mariano-git !! Al parecer era porque tenía los 10 dispositivos que te dan como máximo ya registrados. Borré 2 o 3, tiré el curl y funcionó bien, por lo que volví a probar en Kodi y todo genial. Lo que sí vi es que demoró más de lo que suele demorar en comenzar el streaming, y la programación EGP no me está saliendo. Sabrás qué podrá ser?

Igual eso es lo de menos, lo que espero con esta versión es que me mejore el buffering ja, igualmente creo que eso no depende de la aplicación. Me he roto la cabeza pensando qué puede ser, porque lo más raro es que el buffering suele darse a determinadas horas (desde las 19 hs para arriba). Pienso que puede ser el hardware de la Raspberry 3b+, pero con otros servicios de streaming tipo Youtube no tengo ningún problema y reproduzco en 1920x1080. Entonces ahí es donde me da a pensar que podría ser tema de los servidores de Flow que a determinada hora se saturan. Peeeero con la aplicación web en Chrome NUNCA tengo problemas, por ende también estaría descartado que sea un problema de mi red, además tengo conectada la Raspberry por ethernet directo al router y es muy estable.

Por ende pienso que el problema podría estar en Widevine. He leído en foros que mucha gente tiene problemas de buffering con servicios de IPTV debido a la versión de Widevine. Igualmente he probado con TODAS, y bueno esta versión de Flow anda sólo con la última, y creo que con la penúltima también, y con ambas sigo teniendo buffering.
Lo raro es que, si fuese por Widevine, ¿Por qué el buffering casi siempre se da desde las 19 hs para arriba? 
En fin, vamos a ver si mágicamente se me soluciona el buffering con esta versión ja ja.

Desde ya te agradezco por todo tu trabajo en este plugin y que tu idea sea seguirlo mejorando, cualquier cosa estoy para dar un mano.

Saludos y gracias!!

**Comment by MarcoMiretti** [comment]
Buenas Mariano!

Probé algunas veces más pero sin éxito. Justo la conexión de ese dispositivo es bastante buena (está por eth al router), la mayoría de los servicios de streaming me funcionan bien ahí.

```
LibreELEC:~ # ping web.app.flow.com.ar
PING web.app.flow.com.ar (13.226.52.95): 56 data bytes
64 bytes from 13.226.52.95: seq=0 ttl=240 time=156.719 ms
64 bytes from 13.226.52.95: seq=1 ttl=240 time=156.608 ms
```

Igual no descarto que sea un problema de conexión.

Por lo que puedo ver en la página de personal logra autenticarse como "kodi", pero se ve que le está costando traer los canales/programación.

Muchas gracias!

**Comment by mariano-git** [comment]
@MarcoMiretti , @MaxiReggi 
Estoy viendo que demora mucho en cargar la programacion yo tambien. 
Seguramente es OverHead del framework en dispositivos que no son muy potentes. En mi linux carga rapidisimo... Tengan en cuenta que bajar la guia de programacion es largo por la cantidad de datos irrelevantes que manda flow que no sirven para nada y cada consulta al servidor son varios megas de bajada y proceso...

En mi caso tengo una box android china bastante mala y demora mucho en cambiar de canales y cargar, pero hasta ahora funciono bastante bien.
Voy a ver si mejoro la performance, aunque con todas las vueltas que da Flow no es seguro que pueda mejorarla mucho.

Uno de los cambios es obtener el source del streaming antes era mucho mas rapido pero ahora hay que preguntar nuevamente al servidor por el source y validar la licencia.

Si la programacion se traba por algun motivo hagan esto.

Vayan a la configuracion del plugin. Ponganlo en modo Experto y pongan 0 (cero) en Last Update.
Eso dispara una actualizacion completa. 
Si lo hacen en channels, baja nuevamente todos los canales. Si lo hacen en programas baja toda la guia nuevamente.

![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/63b30dbd-2fb6-4b56-8c84-308d34d4be11)

**Comment by mariano-git** [comment]
@MaxiReggi También veo el problema del almacenamiento en búfer y puedo confirmar que es un problema mixto entre Flow y Kodi.

Al parecer, es como decis, los servidores de Flow están saturados y no responden y eso provoca que el InputStream adaptive se vuelva loco y no se recupere con la rapidez necesaria. No lo ves en el sitio web de Flow porque se recupera mucho más rápido.

Posible solución... Juga un poco con la configuración adaptativa de Inputstream.

Otra cosa a tener en cuenta... No todos los videos DRM (widevine) se pueden reproducir en Full HD debido a los límites impuestos por Widevine.
Por lo que entiendo. Widevine puede funcionar en Hardware (TEE) o Software, y en software la calidad de video permitida es limitada.

El raspberry pi no es TEE. Solo los teléfonos de marca lo son o si tienen procesadores especiales como Qualcomm o la familia ARM Cortex TrustZone, por lo que es muy difícil que puedas reproducir ese contenido.

Con respecto a YouTube... bueno, es Google... y probablemente no todos los videos estén protegidos por DRM o tengan algún truco reservado para ellos...

**Comment by maximilianoreggi** [comment]
Hola @mariano-git !

Perdón por la demora en responder. Te comento que veo mucho mejor esta versión en cuánto al buffering. Anoche me buffereó un poco, pero muy poco en comparación a lo que suele ser, así buenísimo por ese lado! Voy a seguir probándolo.

Peeero, estoy teniendo un problema, que parece que particularmente es con TyC Sports. Puedo ver aproximadamente durante 15 minutos, y después se corta de repente. No sé si pasará con algún canal más, pero con los que he probado es con el único que me ha pasado. El tema es que en los logs parece no haber error. Te copio el log a ver si sabés qué puede ser. Siempre la última línea dice "DASH Full Update", pero esa línea parece no ser un error y la veo antes también en el log.

2023-07-20 16:44:53.143 T:3482    DEBUG <general>: AddOnLog: inputstream.adaptive: Download finished: https://edge-live12-sl.cvattv.com.ar:443/live/c7eds/TyCSport/SA_Live_dash_enc/TyCSport-mp4a_145200_spa=20000-scale=48000-12950969858524.mp4 , avg speed: 1503411.33byte/s, current speed: 979736.00byte/s
2023-07-20 16:44:53.145 T:3484    DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
2023-07-20 16:44:53.145 T:3484    DEBUG <general>: CurlFile::Open(0x594f7f60) https://edge-live12-sl.cvattv.com.ar:443/live/c7eds/TyCSport/SA_Live_dash_enc/TyCSport-CEA708_TTML_und_72971=30000-scale=1000-269811874037.mp4
2023-07-20 16:44:53.182 T:3484    DEBUG <general>: AddOnLog: inputstream.adaptive: Download finished: https://edge-live12-sl.cvattv.com.ar:443/live/c7eds/TyCSport/SA_Live_dash_enc/TyCSport-CEA708_TTML_und_72971=30000-scale=1000-269811874037.mp4 , avg speed: 1501936.46byte/s, current speed: 29138.00byte/s
2023-07-20 16:44:53.252 T:3480    DEBUG <general>: AddOnLog: inputstream.adaptive: Download finished: https://edge-live12-sl.cvattv.com.ar:443/live/c7eds/TyCSport/SA_Live_dash_enc/TyCSport-avc1_2499968=10001-scale=30000-8094356161058.mp4 , avg speed: 2170249.67byte/s, current speed: 2509898.00byte/s
2023-07-20 16:44:54.719 T:3480    DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'connection: keep-alive'
2023-07-20 16:44:54.720 T:3480    DEBUG <general>: CurlFile::Open(0x70cdc1d0) https://edge-live12-sl.cvattv.com.ar:443/live/c7eds/TyCSport/SA_Live_dash_enc/TyCSport-avc1_2499968=10001-scale=30000-8094356221118.mp4
2023-07-20 16:44:54.952 T:3469    DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'If-Modified-Since: Thu, 20 Jul 2023 19:44:52 GMT'
2023-07-20 16:44:54.952 T:3469    DEBUG <general>: CurlFile::ParseAndCorrectUrl() adding custom header option 'If-None-Match: ""542d08d2-8ec7-0000000064b98eb4-0000000064b98eb5;36551-gzip""'
2023-07-20 16:44:54.952 T:3469    DEBUG <general>: CurlFile::Open(0x48f07ab0) https://edge-live12-sl.cvattv.com.ar:443/live/c7eds/TyCSport/SA_Live_dash_enc/TyCSport.mpd
2023-07-20 16:44:55.005 T:3469    DEBUG <general>: AddOnLog: inputstream.adaptive: Download finished: https://edge-live12-sl.cvattv.com.ar:443/live/c7eds/TyCSport/SA_Live_dash_enc/TyCSport.mpd
2023-07-20 16:44:55.005 T:3469    DEBUG <general>: AddOnLog: inputstream.adaptive: DASH Full update (w/o startnum): repid: avc1_379968=10005 current_start:79200

Gracias! Saludos!!!

**Comment by pikenon** [comment]
Buenas!! Tardé en contestar porque no tuve tiempo para probar las posibles soluciones. El tema es que no lo puedo hacer funcionar aun ni en Windows ni en Android. Me tira errores diferentes en ambas versiones, pero por ahora te comento lo que me sucede en Kodi-Windows 10.
Ya no me da errores explícitos, pero NO LOGRO que me aparezcan los canales. Me aparece todo vacío en la sección TV. Tengo la cuenta bien configurada (usuario y contraseña de flow), hice limpieza de dispositivos en la cuenta flow. Pero no logro que me aparezcan canales. Intenté el Auto Configure IPTV Simple Cliente, pero no hay caso, sigue todo vacía la grilla de canales. 
Te paso alguna captura e información:

En el kodi.log, el único error que veo (relativo a este tema) es:
2023-08-06 01:31:07.940 T:15788   error <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::PlaylistLoader::LoadPlayList - Playlist file path is not configured. Channels not loaded.
2023-08-06 01:31:07.942 T:10476   error <general>: GetChannelGroups: Add-on 'pvr.iptvsimple' returned an error: server error
2023-08-06 01:31:07.943 T:10476   error <general>: GetChannels: Add-on 'pvr.iptvsimple' returned an error: server error
2023-08-06 01:31:07.943 T:10476   error <general>: GetChannelGroups: Add-on 'pvr.iptvsimple' returned an error: server error
2023-08-06 01:31:07.943 T:10476   error <general>: GetChannels: Add-on 'pvr.iptvsimple' returned an error: server error

Captura de configuracion "general" en IPTV Simple Clieent.. me extraña que la URL de M3U esté vacía
![image](https://github.com/mariano-git/plugin.video.flow/assets/73316976/243b473b-2de0-475c-9c0f-eb5cda9f5497)

Captura de configuracion "EPG", me extraña que XMLTV URL esté vacía
![image](https://github.com/mariano-git/plugin.video.flow/assets/73316976/24d58716-015b-46d8-a7b2-bbaaacfc4b7a)

Estoy estancado y no se qué más probar. Incluso probé borrar y re instalar los add on (IPTV, el de Flow, etc.)
Si soluciono el de Windows, después comento el error que me tira en el Kodi de Android.

**Comment by mariano-git** [comment]
@MaxiReggi @MarcoMiretti @pikenon @maximilianoreggi 
 Chicos, cierro este issue porque considero que la version esta funcionando.

@pikenon Abri un issue para tu caso, la seguimos aca: https://github.com/mariano-git/plugin.video.flow/issues/18

**Comment by capoandres** [comment]
Hola como están. Soy muy novato y ni siquiera puedo conseguir instalar el plugin ni el repositorio. Alguna guía más detallada para ver como funciona esto en Kodi se los agradecería.

**Comment by mariano-git** [comment]
> Hola como están. Soy muy novato y ni siquiera puedo conseguir instalar el plugin ni el repositorio. Alguna guía más detallada para ver como funciona esto en Kodi se los agradecería.

Hola @capoandres 

Fijate aca:
https://www.softzone.es/programas/multimedia/anadir-addons-kodi/
y aca:
https://github.com/mariano-git/plugin.video.flow/issues/2
