### ISSUE TITLE
Attribute Error: 'NoneType" object has no attribute 'getFamily'

### ISSUE THREAD

**Issue by MaxiReggi** [mariano-git/plugin.video.flow#17]
Hola @mariano-git !

Dejo un error que estoy teniendo hace 3 días y no me deja cargar ningún canal.

[plugin_flow_error.txt](https://github.com/mariano-git/plugin.video.flow/files/12164461/plugin_flow_error.txt)

Muchas gracias! 
Saludos

**Comment by mariano-git** [comment]
Hola @MaxiReggi 

Los de Flow se enojaron con el KODI...
Recien termine un fix...
Lo pruebo y si todo anda bien manana lo subo...
Pone todo en automatico asi se instala solo...

![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/976c39a2-8aa2-4bd7-9e69-49c419b48776)
![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/03dc1acc-776e-476f-8ca0-e7df970d36fa)
![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/95a26965-27c5-4616-ad8e-d9bdff31a066)

![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/8d977222-0951-43eb-ab68-ab9c1105f317)

**Comment by MaxiReggi** [comment]
Hola @mariano-git 

Jaja, no me digas que hicieron algo para romperlo. En fin, dale nomás, espero la actualización!

Muchas gracias como siempre!
Saludos!

**Comment by mariano-git** [comment]
Listo! @MaxiReggi 

Si no updatea solo, forzalo...

![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/a9422994-1603-453b-887e-5588de7d2d5b)

**Comment by MaxiReggi** [comment]
Genio!! Ya está funcionando de vuelta!

Mil gracias!

Voy a ver si puedo mejorar un poco el tema del buffering que ya no es tanto como antes. Justo el fin de semana estuve
tocando la configuración del inputstream adaptive y después de tocar eso no había buffereado más, pero bueno quizás fue casualidad. Vamos a ver qué pasa probándolo un poco ahora, te cuento si encuentro una configuración que lo mejore.

Saludos y gracias de vuelta!!

**Comment by mariano-git** [comment]
@MaxiReggi Cierro el issue porque no volviste a postear nada y lo considero resuelto.

Saludos!!

**Comment by maximilianoreggi** [comment]
Hola Mariano!

Justo ayer que lo cerraste volvió a suceder este mismo error jeje, de no creer.

Adjunto el log pero entiendo que es igual porque el mensaje es el mismo:
Attribute Error: 'NoneType" object has no attribute 'getFamily'

[ErrorKodi.txt](https://github.com/mariano-git/plugin.video.flow/files/12305680/ErrorKodi.txt)

Saludos y gracias!!!

PD: soy Maxi pero con la cuenta de GitHub del laburo, perdón pasa que todo un lío loguearse y desloguearse.

**Comment by mariano-git** [comment]
Hola @maximilianoreggi 

Es facil de arreglar... Despues armo un update para esos valores experto queden seteados x default...
En parte es culpa mia y en parte por Flow...

En los settings del plugin **cambia los valores que estan en rojo como figuran en la imagen y dale OK!! 
Contame como te va dsps!!**

![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/97d7c77c-11fd-4b51-8484-ac23448a268c)

**Comment by maximilianoreggi** [comment]
Hola @mariano-git !

Impecable, cambié eso y volvió a andar! Podés cerrar el issue!!

Mil gracias! Saludos!

**Comment by mariano-git** [comment]
Abierto para documentacion.

**Comment by mariano-git** [comment]
Issue cerrado.
