### ISSUE TITLE
KODI 20

### ISSUE THREAD

**Issue by mariano-git** [mariano-git/plugin.video.flow#18]
Buenas!! Tardé en contestar porque no tuve tiempo para probar las posibles soluciones. El tema es que no lo puedo hacer funcionar aun ni en Windows ni en Android. Me tira errores diferentes en ambas versiones, pero por ahora te comento lo que me sucede en Kodi-Windows 10.
Ya no me da errores explícitos, pero NO LOGRO que me aparezcan los canales. Me aparece todo vacío en la sección TV. Tengo la cuenta bien configurada (usuario y contraseña de flow), hice limpieza de dispositivos en la cuenta flow. Pero no logro que me aparezcan canales. Intenté el Auto Configure IPTV Simple Cliente, pero no hay caso, sigue todo vacía la grilla de canales. 
Te paso alguna captura e información:

En el kodi.log, el único error que veo (relativo a este tema) es:
2023-08-06 01:31:07.940 T:15788   error <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::PlaylistLoader::LoadPlayList - Playlist file path is not configured. Channels not loaded.
2023-08-06 01:31:07.942 T:10476   error <general>: GetChannelGroups: Add-on 'pvr.iptvsimple' returned an error: server error
2023-08-06 01:31:07.943 T:10476   error <general>: GetChannels: Add-on 'pvr.iptvsimple' returned an error: server error
2023-08-06 01:31:07.943 T:10476   error <general>: GetChannelGroups: Add-on 'pvr.iptvsimple' returned an error: server error
2023-08-06 01:31:07.943 T:10476   error <general>: GetChannels: Add-on 'pvr.iptvsimple' returned an error: server error

Captura de configuracion "general" en IPTV Simple Clieent.. me extraña que la URL de M3U esté vacía
![image](https://github.com/mariano-git/plugin.video.flow/assets/73316976/243b473b-2de0-475c-9c0f-eb5cda9f5497)

Captura de configuracion "EPG", me extraña que XMLTV URL esté vacía
![image](https://github.com/mariano-git/plugin.video.flow/assets/73316976/24d58716-015b-46d8-a7b2-bbaaacfc4b7a)

Estoy estancado y no se qué más probar. Incluso probé borrar y re instalar los add on (IPTV, el de Flow, etc.)
Si soluciono el de Windows, después comento el error que me tira en el Kodi de Android.

_Originally posted by @pikenon in https://github.com/mariano-git/plugin.video.flow/issues/16#issuecomment-1666711610_

**Comment by mariano-git** [comment]
Hola @pikenon

Creo que el problema es porque estas en Kodi 20 y el plugin todavia no llego ahi.
Pero dado que estas en Windows y con Kodi 20 viene bien para ir avanzando con esa migracion y verificacion.

En principio por las capturas veo que el IPTV Simple no estaria configurado correctamente ya que entre Kodi 19 y 20 deben haber cambiado las cosas...

Intentemos configurarlo y ver que pasa...

Vas a tener que investigar un poco, pero no estan complicado tampoco.

KODI genera un directorio donde guarda la configuracion del usuario.
En linux es `/home/[user]/.kodi`
En windows segun la documentacion (que no siempre esta bien) seria algo asi como:
`C:\Users\<YourUsername>\AppData\Roaming\Kodi`

Mas info aca: https://kodi.wiki/view/Userdata

Dentro de esas carpetas deberia existir otra llamada `userdata/addon_data` y dentro de esa, otra con el nombre del plugin (plugin.video.flow)

Si el plugin esta funcionando bien, en ese directorio vas a encontrar 2 archivos con el nombre **flowtv** 
Si esos archivos no existen entonces hay otro problema...

En el IPTV Simple Client configura el que es M3U en donde dice M3U  y el XML donde habla sobre XMLTV.

Seguramente debe haber otros seteos para afinar, pero esos son los esenciales.

Avisame como te va y gracias por arriesgarte y usar KODI 20 porque viene barbaro para ir preparando el soporte!

**Comment by mariano-git** [comment]
Cerrando issue por falta de actividad...

**Comment by pikenon** [comment]
Perdón por la colgada pero no había tenido tiempo de probar. No se si este issue sigue apto para escribir, pero acá va:
Hice las verificaciones que me pediste y pasa lo siguiente:
-En Windows: solucionado. Escribí a mano los path de los archivos m3u y XML y santo remedio.
-En Android intenté hacer lo mismo. Ahora en las opciones de TV del KODI me aparecen los canales. Pero tengo un problema con la app de Personal. Me tira un error y me dice que verifique el registro. Acá dejo el LOG con los errores que tienen que ver con lo que me está pasando. Ya intenté limpiar caché y volver a instalar la APP pero pasa lo mismo.

[kodi -errors-.log](https://github.com/mariano-git/plugin.video.flow/files/12709734/kodi.-errors-.log)

**Comment by mariano-git** [comment]
Hola @pikenon 

Bueno, hasta aca llegamos con cuentiones que se podian solucionar facil.
Y si bien esta tambien seria facil, va a llevar mucho tiempo.

KODI 19 usa python 3.8 o 3.9 y KODI 20 usa python 3.11.
Los genios de python introdujeron cambios incompatibles en 3.11 y lo que estas viendo es a causa de:

_**Remove deprecated aliases to [Collections Abstract Base Classes](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes) from the [collections](https://docs.python.org/3/library/collections.html#module-collections) module. (Contributed by Victor Stinner in [bpo-37324](https://bugs.python.org/issue?@action=redirect&bpo=37324).)**_

Lo cual solo se puede corregir modificando el codigo.

```
# In python version 3.10 you should import Iterable from collections.abc instead:
# from collections.abc import Iterable
# or you can:

try:
    from collections.abc import Iterable
except ImportError:
    from collections import Iterable
```

Ahora estoy algo limitado de tiempo y no puedo, pero si sabes python podes encararlo vos hace un PR

**Comment by pikenon** [comment]
Me imaginé que era algo así. La verdad es que no tengo idea de Python  jeje.
Aclaro que en Windows también uso KODI 20 y ahí logré que funcione perfecto.
De todas maneras te agradezco enormemente el tiempo dedicado en responder los problemas.
