### ISSUE TITLE
ERROR <general>: plugin.video.flow: ERROR: piggy.base.overload.invocables.Invocables: Error processing overloading

### ISSUE THREAD

**Issue by MaxiReggi** [mariano-git/plugin.video.flow#19]
Hola @mariano-git !

Sabés que hacer varios días que no puedo ver nada, primero que no me carga la programación, y segundo cuando quiero ver algo me tira este error que pongo en el titulo del issue.

Por lo que veo es al hacer este Post:
POST /auth/v2/provision/login HTTP/1.1"

Y está retornando un 404

Te dejo el log!

[kodi-error.log](https://github.com/mariano-git/plugin.video.flow/files/12384377/kodi-error.log)

Mil gracias!
Saludos

**Comment by mariano-git** [comment]
Hola @MaxiReggi 

No tengo ese problema. De hecho force que actualizara y todo bien...

Fijate la fecha y la hora del log.

```
2023-08-18 21:35:40.338 T:11763    INFO <general>: plugin.video.flow: INFO: plugin.stage.executioncontext.ExecutionContext.ProgramsRetriever: 
                                                                                                       ********************************************
                                                                                                       Saving xml programs: "/home/mariano/.kodi/userdata/addon_data/plugin.video.flow/flowtv.xml" 
                                                                                                       ********************************************

2023-08-18 21:35:40.683 T:11738   DEBUG <general>: CGLContextEGL::SwapBuffers: sync check blocking
```
Un 404 podria ser un cache viejo (raro, pero seria posible) **Reinicia todo por las dudas!!**

**Comment by gastongg** [comment]
Hola Mariano! Cómo estás? Che tengo un problema y es que no sé bien cómo configurar el flow, resulta que he instalado todo lo necesario, puse y mi usuario y contraseña y cuando lo quiero abrir me dice que hay un error y me fijé en el archivo de información estoy corriendo libreelect en una epic 3b+ y no me estoy dando cuenta dónde puedo encontrar este archivo para ver la info que dice, me ayudarías a configurarlo si no es mucha molestia?

**Comment by maximilianoreggi** [comment]
Hola @mariano-git ,perdón por la demora en responder, no estuve en mi casa estos días para hacer pruebas.

Al parecer era algún tema mío, porque desinstalé todo, volví a instalar y todo bien.

Espero no surja más nada ja!

Muchas gracias!
Saludos,

**Comment by mariano-git** [comment]
Cierro el issue @gastongg la seguimos aca https://github.com/mariano-git/plugin.video.flow/issues/20
