### ISSUE TITLE
Me ayudarías a configurarlo si no es mucha molestia?

### ISSUE THREAD

**Issue by mariano-git** [mariano-git/plugin.video.flow#20]
Hola Mariano! Cómo estás? Che tengo un problema y es que no sé bien cómo configurar el flow, resulta que he instalado todo lo necesario, puse y mi usuario y contraseña y cuando lo quiero abrir me dice que hay un error y me fijé en el archivo de información estoy corriendo libreelect en una epic 3b+ y no me estoy dando cuenta dónde puedo encontrar este archivo para ver la info que dice, me ayudarías a configurarlo si no es mucha molestia?

_Originally posted by @gastongg in https://github.com/mariano-git/plugin.video.flow/issues/19#issuecomment-1696383768_

**Comment by mariano-git** [comment]
Hola Gaston! (@gastongg)

Contame aca bien que problema estas teniendo y vemos que es lo que esta haciendo falta.

Saludos!!

**Comment by gastongg** [comment]
Hola Mariano, en principio que creo no lo estoy instalando bien, no entiendo mucho como instalarlo, una vez lo instale en kodi 20 y me dió para instalar algo de Piggy o algo así. Después de leer que en el 20 no anda, baje a la versión 19 matrix pero, cuando lo instaló no me da estás 3 cosas para instalar (el nombrado anteriormente PIGGY) Y solo me instaló flow personal pero no anda (aclaro que tengo el pvr iptv simple cliente instalado y todo lo necesario) también ví que hay una versión nueva pero no ni donde está o como es el link del repositorio. Podrías darme una mano?

**Comment by mariano-git** [comment]
Bueno, a ver...

Primero, Bajate el repositorio (es un archivo zip) en la jerga de Kodi...
https://github.com/mariano-git/repository.mariano-git/blob/matrix/repository.mariano-git-1.0.0.zip

Instalas el repo como dice aca:
https://kodi.wiki/view/Archive:Install_add-ons_from_zip_files#:~:text=Install%20from%20zip%20file%20allows,at%20the%20time%20of%20installation

o como dice aca:

https://www.softzone.es/programas/multimedia/anadir-addons-kodi/

Eso deberia instalar el Flow, los Piggy y varios componentes.

![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/d3a8a69c-be3c-4980-a5ef-92312304ab5a)

Luego tenes que instalar Widevine porque los videos de Flow estan encriptados...

![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/7bde5b9f-41df-47b7-b8ae-eb217a700cd4)

Finalmente configuras el Flow Plugin con tu usuario y password y le das a Configure IPTV como en la imagen

![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/e9c9ec17-0ed5-457e-8d56-7073084340da)


Por ultimo....

Aplica el Fix que dice aca...

https://github.com/mariano-git/plugin.video.flow/issues/17#issuecomment-1672354111


Una vez que este eso, hay que esperar que refresque los canales y la programacion y si ves que no pasa nada, busca el log de Kodi y subimelo...

https://kodi.wiki/view/Log_file

Contame como te fue...

**Comment by mariano-git** [comment]
Cerrando issue por inactividad

**Comment by gastongg** [comment]
Hola, el problema que tengo es que al cargar el link me dice que no puede conectarse al servidor remoto y pongo todo tal cual está pero, surge el error...

**Comment by mariano-git** [comment]
Hola @gastongg 

Necesito mas info para realmente saber que pasa...

**Comment by gastongg** [comment]
> Hola @gastongg 
> 
> Necesito mas info para realmente saber que pasa...
> 

Listo, solucionado, no me dejaba descargar desde el repo, me daba un error la direccion, lo solucione rajando el archivo zip e instalado desde el zip
