### ISSUE TITLE
Playback failed

### ISSUE THREAD

**Issue by todotirreno** [mariano-git/plugin.video.flow#21]
Al presionar en algún canal de Flow, luego de unos segundos se abre un cuadro de error:
"Playback failed. One or more items failed to play."
Apliqué [esta corrección](https://github.com/mariano-git/plugin.video.flow/issues/17#issuecomment-1672354111) pero no se soluciona.

[log](https://github.com/mariano-git/plugin.video.flow/files/13759799/kodi.log)
Uso Kodi 19.5 en Android TV
Es la primera vez que la instalo.

**Comment by mariano-git** [comment]
hola @todotirreno 

Estuve mirando tu log y no veo un problema concreto, solo que el servidor de licencias de flow dio error.
Como consejo podes verificar si tenes intalado el input stream adaptive, pero no creo que sea ese el problema.
Avisame si seguis viendo el mismo problema e intentamos otras cosas.

Saludos!

**Comment by todotirreno** [comment]
Muchas gracias por responder.
Confirmo que InputStream Adaptive está instalada. Y que sigue el mismo problema.

Se me ocurrió probar en **Windows 11**/Kodi 19.4 y tuve exactamente el mismo problema. Entonces empecé a tocar un poco en Windows. No tuve suerte en el momento de hacer cambios, pero hoy volví a probar y funcionó normalmente. Cosas que creo que hice:
-En InputStream Helper "reinstall Widevine CDM library" o alguna de las otras opciones similares debajo, no me acuerdo exactamente.
-En mi cuenta de Flow tenía llena de dispositivos Kodi, se ve que por hacer tantas pruebas. Eliminé todos los dispositivos. 
-En el addon de Personal Flow -> EPG -> Auto configure IPTV Simple Client

Lamentablemente en **Android TV no le encuentro la vuelta** y sigue el mismo problema. En InputStream Helper no aparece opción para instalar Widevine porque creo que ya viene con Android?

**Comment by mariano-git** [comment]
No podria confirmarte, pero creo que si el android no tiene Play Store services probablemente no tenga Widevine.

Fijate si aplicaste este fix https://github.com/mariano-git/plugin.video.flow/issues/17#issuecomment-1672354111

Ademas tenes una opcion de activar el logger a nivel debug, va a generar muchisima info y ahi quizas salte cual es el problema.

Aca te muestra como activarlo

![image](https://github.com/mariano-git/plugin.video.flow/assets/28299309/816ccf95-dd31-44b0-ac91-949ea8d07e65)

**Comment by todotirreno** [comment]
Tiene Google Play Services y sí, ya estaba aplicada [#17 (comment)](https://github.com/mariano-git/plugin.video.flow/issues/17#issuecomment-1672354111).
[log con nivel depurador](https://github.com/mariano-git/plugin.video.flow/files/13814150/kodi.log)

**Comment by mariano-git** [comment]
Bueno, si practicamente es el mismo error que me mandaste en el log anterior.
Es un error 500 del servidor cuando se gestiona la licencia para reproducir el contenido DRM.

```
2024-01-02 15:57:10.574 T:28349   DEBUG <general>: CurlFile::Open(0xc410f580) https://prm03.cvattv.com.ar:9194/policy_manager/v3/drm_proxy/Widevine
2024-01-02 15:57:10.857 T:28349   ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 500
2024-01-02 15:57:10.857 T:28349   ERROR <general>: CCurlFile::Open failed with code 500 for https://prm03.cvattv.com.ar:9194/policy_manager/v3/drm_proxy/Widevine:
                                                   
2024-01-02 15:57:10.858 T:28349   ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
```

 Vi que probaste con ESPN...
A que se puede deber ese error la verdad que no lo se porque es un error en el servidor de flow.

**Lo que podemos hacer es probar forzando un refrezco de todos los tokens y ver que pasa... por si quedaron desincronizados...**

Edita el archivo `settings.xml `en `kodi/userdata/addon_data/plugin.video.flow` y ahi pone 0 (cero) en todas las configuraciones que veas que terminan en **_.last_**
Ejemplo: `<setting id="epg.channels.last">`

Una vez que hagas eso tendrias que esperar que el plugin recupere la lista de canales y programas desde flow.
Te vas a dar cuenta porque el log va a escribir **Saving xml programs**,  Tenes que esperar el que dice programs, hay uno anterior pero es de channels...
```
********************************************
Saving xml programs: "/xxxxxxxxxxxxx/xxxxxxxxx/.kodi/userdata/addon_data/plugin.video.flow/flowtv.xml" 
********************************************
```
Ahi activas el log depurador e intenta hacer el play de un canal o programa. 
Eso va a activar un refresh de los tokens DRM y ahi vemos si da un error 500 nuevamente o que pasa.

**Comment by todotirreno** [comment]
Edité settings.xml, esperé a "saving xml programs" y luego intenté reproducir un canal. 
[log](https://github.com/mariano-git/plugin.video.flow/files/13821922/kodi.log) (el log depurador ya estaba activado desde el principio, no me di cuenta)
Creo que sigue el mismo error.

**Comment by mariano-git** [comment]
Me mandaste el mismo log de https://github.com/mariano-git/plugin.video.flow/issues/21#issuecomment-1874612321

**Comment by todotirreno** [comment]
Me confundí, disculpas.
[log](https://github.com/mariano-git/plugin.video.flow/files/13830544/kodi.log)

**Comment by mariano-git** [comment]
Bueno, veo que sigue con el mismo error.

Lamentablemente no puedo ayudarte porque esto ya no parece ser un error del plugin en si.
La unica opcion para que sea un problema del plugin es que haya algo mal en la generacion de los tokens pero eso ya lo probamos.
Aunque resta la opcion que sea algo sistematico de tu cuenta y los tokens se generen mal siempre... seria raro... pero podria ser... 
Pero por otro lado me comentaste que funciono bien en Windows asumiendo que usaste el mismo usuario y password asi que eso lo descartaria...

Vas a tener que intentar debuguearlo vos de alguna manera, aunque de todas formas es algo muy dificil ya que esa llamada es binaria y la ejecuta inputstream.adaptive y delega la informacion a widevine.

Lo que queda es que me compartas el settings.xml, pero ahi va a estar tu usuario y password... Pero... Aun asi tampoco podria asegurarte de encontrar el problema dado que podria ser algo de Widevine o del mismo android...

**Comment by mariano-git** [comment]
Cierro el issue dado que para encontrar el problema seria necesario contar con el equipo fisico y eso no es posble.
