### ISSUE TITLE
Canal incorrecto

### ISSUE THREAD

**Issue by MaxiReggi** [mariano-git/plugin.video.flow#22]
Hola Mariano!

Te hago una consulta. Hace tiempo que por algún motivo, tengo un canal en la grilla que no pertenece a la cuenta con la que estoy logueado. Más específicamente, en lugar de tener el Canal 12 de acá de Córdoba, me aparece el Canal 13 de Buenos Aires. 

Sabrás por qué puede pasar eso y cómo solucionarlo?

Muchas gracias!
Saludos,

Maxi

**Comment by mariano-git** [comment]
Hola Maxi,

La verdad no tengo idea. Como sale en otros dispositivos? No tengo conocimiento de canales especiales por localidad, al menos que sea algun hack que hace la aplicacion

**Comment by mariano-git** [comment]
Cierro por falta de actividad
