### ISSUE TITLE
Addon Flow no genera archivo m3u y xml

### ISSUE THREAD

**Issue by djgerman10** [mariano-git/plugin.video.flow#23]
NO LOGRO que me aparezcan los canales. Me aparece todo vacío en la sección TV. Tengo la cuenta bien configurada (usuario y contraseña de flow), hice limpieza de dispositivos en la cuenta flow. Pero no logro que me aparezcan canales. Intenté el Auto Configure IPTV Simple Cliente
En C:\Users\<YourUsername>\AppData\Roaming\Kodi\userdata\addon_data no me genera los archivos flowtv uno m3u y otro xml
que se podrá hacer ya reinstale kodi desinstale y lo volví a instalar el addon y no me genera dicho archivo que es el que carga los canales
tengo el Kodi 20.5 y el addon de flow 1.5.2

**Comment by djgerman10** [comment]
Aplique este fix y le puse que actualice los canales todos los días y funsiono https://github.com/mariano-git/plugin.video.flow/issues/17#issuecomment-1672354111

**Comment by mariano-git** [comment]
Hola @djgerman10 

Me alegro que haya funcionado. Cerra el Issue una vez que estes conforme!
