### ISSUE TITLE
Error al ingresar usuario y contraseña

### ISSUE THREAD

**Issue by MaxiReggi** [mariano-git/plugin.video.flow#27]
Hola Mariano! Tanto tiempo..

Te comento que hace unos 2 meses que estoy sin poder usar el plugin. Un día me dejó de funcionar, y lo que hice fue volver todas las configuraciones a por default (tanto del plugin como del iptv simple), volver a ingresar contraseña y password, pero nada.
Te dejo el error que me tira la ingresar user y pass en el plugin.

[Kodi-Flow-Error.txt](https://github.com/user-attachments/files/16103083/Kodi-Flow-Error.txt)

Quedo atento!

Saludos y gracias,

Maxi

**Comment by MaxiReggi** [comment]
Recién leo lo del otro issue abierto....es por ese cambio en la validación de user y pass con captcha?

Calculo que debe tener que ver con eso :(

**Comment by mariano-git** [comment]
Hola @MaxiReggi,

Si, lamentablemente ese es el problema... :-(

Seria bueno contar con ayuda a ver si algun otro plugin pudo resolver algo parecido.

Queda una alternativa y es usar otra API que no sea web. Pero tienen 2 problemas.
1.- Son mas duras de entender.
2.- Probablemente hagan que el dispositivo se vea como un "SmartTV" y hay pocos disponibles.

La interface web de Flow ha mejorado bastante, pero el reproductor sigue siendo un asco...

**Comment by mariano-git** [comment]
Mas info aqui: https://github.com/mariano-git/plugin.video.flow/issues/26
