### ISSUE TITLE
Configuración óptima en Kodi?

### ISSUE THREAD

**Issue by MaxiReggi** [mariano-git/plugin.video.flow#4]
@mariano-git 

Hola Mariano, en primer lugar felicitarte por este plugin, lo vengo usando desde Febrero aproximadamente, anda muy bien!. He ido mejorando su funcionamiento para evitar el buffering en Kodi con diferentes configuraciones, pero muy de vez en cuando sigue buffereando y quizás haya alguna configuración que pueda mejorar aún más.

Muestro a continuación todas las configuraciones que he tocado para que me digas si hay algo que pudiese estar faltando (Uso OSMC en una Raspberry Pi 3b+, con Kodi Matrix 19) 

* Configuracion de caché en advancedSettings.xml

memorysize 20971520
buffermode 1
readfactor 4.0

* Configuración InputStream Adaptive:

Max Resolution general decoder: 1080p
Max Resolution secure decoder: 1080p

(En 720p el buffering era mínimo antes de pasarlo a 1080)

* Configuración Settings/Player:

Adjust display refresh rate: On start/stop
Sync playback to display: Desactivado
Allow using DRM PRIME decoder: Activado
Allow hardware acceleration: Activado

(Cuando desactivaba la aceleración por hardware también el buffering era casi nulo)

En estos días prácticamente logre reducir al máximo el buffering actualizando el firmware de mi router a la última versión. Uso un Asus RT-AC86u, con el firmware Merlin. Vale mencionar que la Raspberry la uso siempre conectada por cable ethernet, nunca por wifi. Tengo un ancho de banda de 15 Mb/s, suele llegar a 17 Mb, muy estable.

Por último, dejo el log que tira la app cuando hay buffering:

2022-04-15 14:38:59.495 T:460   WARNING <general>: ActiveAE - large audio sync error: -5271.403076

Estuve investigando sobre este error, y al parecer es común en los clientes IPTV en Kodi, y por lo que leí, generalmente pasa con los streams codificados con Audio ACC (no sé si será el caso de Flow).

Desde ya muchísimas gracias y gracias por este gran plugin!!

**Comment by mariano-git** [comment]
Hola Maxi!!

Gracias por los comentarios!! Me pone muy contento que puedas usar el plug in y te sirva!!

El buffering es algo muy complicado de resolver porque muchos factores y componentes estan involucrados, y obviamente que a mayor resolucion, mayor ancho de banda vas a necesitar.

Dicho esto, no creo que el plugin te este dando problemas con eso, peeero (siempre hay un pero...) El plugIn si hace uso de un componente que podria estar desactualizado y hoy justamente vi que se ha publicado una nueva version (hace 2 dias) que quizas solucione el problema.

Te aconsejo que revises e instales la ultima version. Aqui abajo te dejo el link.
https://github.com/xbmc/inputstream.adaptive

Saludos y muchas gracias!!

**Comment by mariano-git** [comment]
Cerrando issue
