### ISSUE TITLE
No lo puedo hacer andar

### ISSUE THREAD

**Issue by ChinoLuis** [mariano-git/plugin.video.flow#6]
Por favor. Sigo todos los pasos y no logro hacerlo andar. Flow en Kodi

**Comment by mariano-git** [comment]
Hola Chino,
Pasame un poco mas de info. En que sistema estas corriendo Kodi? Estas viendo algun error?

**Comment by ChinoLuis** [comment]
Hola Mariano. Muchas gracias por contestar. Logré hacerlo andar. Actualicé dependencias cómo dijiste en un comentario anterior. Y comenzó a funcionar. Excelente trabajo! 👏 👏. Y una última consulta. El contenido que tiene Flow cómo promoción. Cómo series y producciones propias. Se puede ver?. Porque sólo activé los canales. Repito. Excelente trabajo!

**Comment by mariano-git** [comment]
Buenisimo Chino, me alegro mucho que funcione!!. Lamentablemente estoy con poco tiempo para dedicarle y no he tenido tiempo para programar mas opciones. Tengo planeado agregar todo el contenido on-demand en versiones futuras a medida que vaya contando con el tiempo suficiente.

**Comment by ChinoLuis** [comment]
Gracias Mariano. Y el Kodi que utilizo es Matrix v19.4
