### ISSUE TITLE
No abre

### ISSUE THREAD

**Issue by Shunkor** [mariano-git/plugin.video.flow#7]
Hola capo, recien quise probarlo, instale todo, entre configure usuario y pass pero no abre, sabes si aun es compatible?

**Comment by mariano-git** [comment]
Hola @Shunkor Fijate aca https://github.com/mariano-git/plugin.video.flow/issues/5#issuecomment-1238610096

**Comment by Shunkor** [comment]
ok en un rato pruebo, gracias, usas ds?

**Comment by Shunkor** [comment]
te dejo el log para que veas, cuando quiero reproducir un canal da error "EN WINDOWS" kodi en un TVBOX con android funciona perfecto

[https://raw.githubusercontent.com/Shunkor/logKodi/main/Log?token=GHSAT0AAAAAAB3S7IONSCI353SED6ZBM4Q4Y37PRTQ](url)

**Comment by mariano-git** [comment]
> ds

Nope

**Comment by mariano-git** [comment]
> te dejo el log para que veas, cuando quiero reproducir un canal da error "EN WINDOWS" kodi en un TVBOX con android funciona perfecto
> 
> [https://raw.githubusercontent.com/Shunkor/logKodi/main/Log?token=GHSAT0AAAAAAB3S7IONSCI353SED6ZBM4Q4Y37PRTQ](url)

No encuentro nada en ese link... Subilo aca....

**Comment by Shunkor** [comment]
Ahi te invite como colaborador asi lo ves sorry no me percate de ese detalle.
voy a estudiar el codigo, si tenes pensado o estas con el tema de los videos on demand avisa.

**Comment by mariano-git** [comment]
> > [https://raw.githubusercontent.com/Shunkor/logKodi/main/Log?token=GHSAT0AAAAAAB3S7IONSCI353SED6ZBM4Q4Y37PRTQ](url)

SIgo sin poder abrirlo... Subilo aca (https://github.com/mariano-git/plugin.video.flow/issues/5#issuecomment-1240633597)

![image](https://user-images.githubusercontent.com/28299309/203879112-795e91a3-ae30-453a-9c96-3c8a21357dd9.png)

**Comment by mariano-git** [comment]
> Ahi te invite como colaborador asi lo ves sorry no me percate de ese detalle. voy a estudiar el codigo, si tenes pensado o estas con el tema de los videos on demand avisa.

Que tenes en mente?

**Comment by mariano-git** [comment]
@Shunkor 
**AddOnLog: inputstream.adaptive: Unable to load widevine shared library (C:\Users\Shunko\AppData\Roaming\Kodi\cdm\widevinecdm.dll)**

Ese es el problema... tenes que instalar el runtime de widevine para que funcione en Windows (en Linux tmb, pero en android no hace falta)
https://youtu.be/LajY2mTbrEA

**Comment by Shunkor** [comment]
> 

La verdad que el codigo es re prolijo, y se nota que tenes tiempo en esto, tendria que ponerme a leer como es el tema, igual estuve probandolo y funciona de diez, no sabria como encarar la parte de ondemand

**Comment by Shunkor** [comment]
> @Shunkor **AddOnLog: inputstream.adaptive: Unable to load widevine shared library (C:\Users\Shunko\AppData\Roaming\Kodi\cdm\widevinecdm.dll)**
> 
> Ese es el problema... tenes que instalar el runtime de widevine para que funcione en Windows (en Linux tmb, pero en android no hace falta) https://youtu.be/LajY2mTbrEA

Lo vi pero sinceramente no le di bola, interprete que estaba todo instalado ya, se ve q siempre algo falta jaja

**Comment by mariano-git** [comment]
Hola! A vos te gustaria colaborar?

Yo tenia planeado agregar la parte on-demand pero no tuve tiempo suficiente
todavia para hacerlo porque es bastante complicado, no tanto por Kodi sino
mas bien por como flow maneja los datos...

Si queres podemos charlar por otro lado... avisame!!
