### ISSUE TITLE
Work this plugin on Kodi + raspberry 3?

### ISSUE THREAD

**Issue by nmapper** [mariano-git/plugin.video.flow#8]
Hi. This plugin works in Kodi + raspberry 3?

Actually I installed it.
In config section enter the email + password 
Switched the "configured" 
And nothing happen.

I'm doing well?

Libreelec 10.0.3 + raspberry pi 3 here.

Rly ty for you work.

------------
Edit: I'm calling the plugin from "addons" instead "TV"

Works like a charm.

Dismiss the issue.

**Comment by mariano-git** [comment]
Closing this issue per @nmapper request. You're welcome!!
