### ISSUE TITLE
It's currently working?

### ISSUE THREAD

**Issue by shurak** [mariano-git/plugin.video.flow#9]
Hello Mariano!

Thank you for the "flow" plugin. I would like to ask if in this current state the plugin it's working or "Personal" changed something and the plugin doesnt work any more.

In the case that the pluging is currently working, I have the problem that, after following the installation guide, the plugin start, and rigth away shows the file browser screen without any warning of what's failing. Do you have any suggestion or procedure to collect the log and see what's going on?

Thank you very much.
Leo

**Comment by mariano-git** [comment]
Hi @shurak You're welcome!
Going to the issues. As you mentioned, indeed, Flow made 2 changes lately, both related to the negotiation of the license to play DRM content. I'm assuming that Android is immune to just one of those changes, sadly the other is a little bit tricky and I needed to change the plugin code. I'm testing it right now and I'll release it shortly. But if you wanna become a beta tester I guess I could prepare a special package so you can test it.
Where are you running Kodi/plugin? Windows, Linux, Android?

Podes escribir en castellano tambien :-)

**Comment by shurak** [comment]
Hello Mariano!

I will gladly be a beta tester. I am currently using kodi on a raspberry pi 3 on the Libreelec 10.0.3 distribution.

(Je si, pero si queda registro para todos en github lo dejo en íngles)

**Comment by mariano-git** [comment]
Closing this issue since it doesn't have new feedback and its stale
